name: Build and Publish

on:
  push:
    branches: [lab-infra]
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Provision resources for dev
        run: |
          APP_VERSION=$(cat package/.appversion)
          if [ $(git tag -l "$APP_VERSION") ]; then 
            echo "App version $APP_VERSION already released. Please update your version in package/.appversion"
            exit 1
          else
            echo "setting artifact version to $(echo $APP_VERSION-${{github.run_number}})"
            echo "ARTIFACT_VERSION=$(echo $APP_VERSION-${{github.run_number}})" >> $GITHUB_ENV
          fi
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn build:appshell
      - run: yarn install
      - run: yarn lint
      - run: yarn typescript
      - run: yarn test
      - run: yarn build:dist
      - run: cp -R omrs-apps/* dist/
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: package/docker/Dockerfile
          push: true
          tags: bahmni/bahmni-lab:${{env.ARTIFACT_VERSION}},bahmni/bahmni-lab:latest
