name: Trigger E2E Workflows
on:
  workflow_run:
    workflows: [Build and Publish]
    types:
      - completed
env:
  ORG_NAME: Bahmni
  EVENT_TYPE: bahmni-next-trigger
  TEST_COMMAND: "npm run next"

jobs:
  trigger-e2e:
      name: Trigger E2E
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
        - name: Create repository_dispatch
          env:
            REPOSITORY_NAME: "bahmni-e2e-tests"
          run: |
            trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'","client_payload":{"testCommand":"'"${TEST_COMMAND}"'"}}')
            if [ $trigger_result == 204 ];then
              echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
            else
              echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
              cat trigger_response.txt
              exit 1
            fi