name: Pull Reqeust

on:
  pull_request:
    branches: [ Bahmni-IPD-master ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: yarn install
      - run: yarn lint
      - run: yarn typescript
      - run: yarn test
      - run: yarn build